function Praetorian() {
    var personagem = {
        Nome: "Praetorian",
        Estilo: "Briga",
        Escola: "Gladiadores de Phalanx",
        Conceito: "Gladiador alienígena",
        Assinatura: "Braços e rosto para o céus!",
        Forca: 5,
        Destreza: 4,
        Vigor: 6,
        Carisma: 2,
        Manipulacao: 1,
        Aparencia: 4,
        Percepcao: 5,
        Inteligencia: 3,
        Raciocinio: 4,
        Prontidao: 4,
        Intimidacao: 4,
        Perspicacia: 1,
        LutaCega: 4,
        Furtividade: 5,
        Sobrevivencia: 3,
        Arena: 1,
        Computador: 2,
        Misterios: 3,
        Estilos: 3,
        Antecedentes: [newCaracteristica("Recursos", 1), newCaracteristica("Fama", 1)],
        NovasPericias: [],
        NovasTecnicas: [],
        NovosConhecimentos: [],
        NovosTalentos: [],
        Gloria: 7,
        Honra: 4,
        Divisao: "Estilo Livre",
        Posto: 9,
        ForcaVontade: 6,
        Chi: 5,
        Saude: 15,
        ManobrasEspeciais: "Buffalo Punch, Kippup, Power Uppercut, Regeneration, Hyper Fist, Toughskin, Foot Sweep, Shock Treatment, Double Hit Kick, Triple Strike, Psychokinetic Channeling, Maka Wara, Punch Defense, Missile Reflection",
        Combos: "",
        Soco: 6,
        Chute: 5,
        Bloqueio: 4,
        Apresamento: 4,
        Esportes: 5,
        Foco: 3
    };
    return calcPC(personagem);
}

const npc = Praetorian();